---
name: CI
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-18.04

    steps:
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install test dependencies.
        run: pip3 install ansible-tower-cli
      
      - name: deploy
        run: |
          tower-cli config host ${{ secrets.ANSIBLE_URL }}
          tower-cli config username ${{ secrets.ANSIBLE_USER }}
          tower-cli config password ${{ secrets.ANSIBLE_PASSWORD }}
          tower-cli config verify_ssl false
          tower-cli job_template list --insecure
          tower-cli job launch --job-template=15 --wait --monitor
          
